title: Algoritmos supervisados y convenciones <br> de anotación para tareas de <br> procesamiento del lenguaje natural
description: Material para el seminario de la carrera de Letras de la UBA

theme: jekyll-theme-midnight
show_downloads: "true"
